apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-ayid
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qyqu-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-ayid@sha256:b536c7710889b54dd32d137b165d047f07e8eaf0d18fcff1717a11bc3c82a301
        name: my-nodejs
        resources: {}
status: {}
