apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-docker-python-rhtap-three-component-scenarios-ozui
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qyqu-tenant/mc-three-scenarios/devfile-docker-python-rhtap-three-component-scenarios-ozui@sha256:ab3b79722934c73e26afda31733b45eacf0f4ab9cfa1d462eb9a8d51354426cb
        name: my-python
        resources: {}
status: {}
